apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
spec:
  provider:
    gcpsm:
      projectID: replace-me-secret-project
      auth:
        workloadIdentity:
          clusterProjectID: replace-me-cluster-project
          clusterLocation: europe-west1
          clusterName: replace-me-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
