appendonly yes
appendfilename appendonly.aof
appendfsync everysec
aof-use-rdb-preamble yes
dir /data
dbfilename dump.rdb
save 900 1
save 300 10
save 60 10000
protected-mode yes
bind 0.0.0.0
aclfile /run/redis/users.acl
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command DEBUG ""
rename-command SHUTDOWN ""
